# Generated by Django 5.2.9 on 2025-12-25 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Yo‘nalish nomi')),
            ],
            options={
                'verbose_name': 'Yo‘nalish',
                'verbose_name_plural': 'Yo‘nalishlar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ustoz F.I.Sh')),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('serial', models.AutoField(primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(help_text='Masalan: CERT-2025-001', max_length=512, unique=True, verbose_name='Sertifikat ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('father_name', models.CharField(max_length=100, verbose_name='Otasining ismi')),
                ('study_start_date', models.DateField(verbose_name='O‘qishni boshlagan sana')),
                ('study_end_date', models.DateField(verbose_name='O‘qishni tugatgan sana')),
                ('certificate_given_date', models.DateField(verbose_name='Sertifikat berilgan sana')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr/', verbose_name='QR kod')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.course', verbose_name='Bitirgan yo‘nalishi')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.teacher', verbose_name='Ustoz')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
    ]
